spring:
  application:
    name: produto-service

  profiles:
    active: dev

  cloud:
    config:
      uri: http://localhost:8888

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/