spring:
  application:
    name: produto-service

  profiles:
    active: dev

  cloud:
    config:
      uri: http://localhost:8888

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 3
        retry-exceptions:
          - java.lang.Throwable

  timelimiter:
    instances:
      timelimiter-busca-id:
        timeout-duration:
          seconds: 10