spring:
  application:
    name: greeting-service

  config:
    import: optional:configserver:http://localhost:8888/

  cloud:
    config:
      uri: http://localhost:8888

  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka