server:
  port: 8100

spring:
  application:
    name: book-service
  datasource:
    username: ${MYSQL_USER:root}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/book_service}
    password: ${MYSQL_PASSWORD:aluno}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  management:
    tracing:
      sampling:
        probability: 1.0

  flyway:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/book_service}
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:aluno}

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 2s


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs