spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devopMarkz/config-server
          clone-on-start: true
          search-paths: '{application}'
        default-label: main

server:
  port: 8888
