spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
server:
  port: 8765

eureka:
  client:
    fetch-registry: true
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
