spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  management:
    tracing:
      sampling:
        probability: 1.0
  application:
    name: exchange-service
  flyway:
    enabled: true
    url: ${DB_URL:jdbc:mysql://localhost:3306/exchange_service}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:aluno}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/exchange_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:aluno}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs
  swagger-ui:
    url: /exchange-service/v3/api-docs