spring:
  application:
    name: cambio-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

server:
  port: 8000