spring:
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
server:
  port: 8765

springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /book-service/v3/api-docs
      - name: exchange-service
        url: /exchange-service/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
