spring:
  application:
    name: greeting-service
  cloud:
    config:
      uri: http://config-server:8888
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: dev
