name: Microservices Continuous Deployment with GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set Docker tag (latest + short SHA)
        id: vars  # Define uma ID para esse passo
        run: |
          echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Images using Docker Compose
        working-directory: ./Microsservicos ATUALIZADOS
        run: docker compose build


      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:${{ github.workflow_sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.workflow_sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/exchange-service:${{ github.workflow_sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/exchange-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.workflow_sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
