name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build Docker Image for Naming Server
      working-directory: ./Microsservicos ATUALIZADOS/naming-server
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/naming-server:latest .